[metadata]
name = pyTecIO
author = Andreas Waldmann
author_email = mail@awaldmann.com
description = Tecplot ASCII data reader
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT license
license_files = LICENSE
include_package_data = True
keywords = tecplot
version = 0.2.0
url = https://github.com/awaldm/pyTecIO

[options.extras_require]
test = 
    pytest
    flake8

[options]
zip_safe = False
package_dir =
    =src
packages = find:
install_requires =
    numpy
    pandas
python_requires = >=3.9

[options.packages.find]
where = src
